---
- name: Create VM resources directory
  ansible.builtin.file:
    path: "{{ vm_resources_dir }}"
    state: directory

- name: Download and verify files
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ vm_resources_dir }}/{{ item.parent }}/{{ item.dest }}"
    checksum: "sha256:{{ item.sha256 }}"
  loop: "{{ files }}"

- name: Compress parent directories into tarballs
  ansible.builtin.archive:
    path: "{{ vm_resources_dir }}/{{ item.name }}"
    dest: "{{ vm_resources_dir }}/{{ item.tarball }}"
    format: gz
  loop: "{{ parents }}"

- name: Remove parent directories
  ansible.builtin.file:
    path: "{{ vm_resources_dir }}/{{ item.name }}"
    state: absent
  loop: "{{ parents }}"

